// <auto-generated />
using System;
using M2.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace M2.Infrastructure.Migrations
{
    [DbContext(typeof(M2DbContext))]
    [Migration("20260514023329_Sprint5_ApiKeys")]
    partial class Sprint5_ApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("m2")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("M2.Domain.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_api_keys_TenantId_KeyHash");

                    b.ToTable("api_keys", "m2");
                });

            modelBuilder.Entity("M2.Domain.Approvals.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EntityType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MaxLevels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("MaxLevels");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Mode");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("IX_approval_policies_TenantId_EntityType");

                    b.ToTable("approval_policies", "m2");
                });

            modelBuilder.Entity("M2.Domain.Approvals.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentStep");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("EntityType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("approval_requests", "m2");
                });

            modelBuilder.Entity("M2.Domain.Approvals.ApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ActedAt");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ApproverId");

                    b.Property<string>("ApproverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ApproverType");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("Comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestId");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("StepNumber");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_approval_steps_RequestId");

                    b.ToTable("approval_steps", "m2");
                });

            modelBuilder.Entity("M2.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClockInAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ClockInAt");

                    b.Property<DateTimeOffset?>("ClockOutAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ClockOutAt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "ClockInAt")
                        .HasDatabaseName("IX_attendance_records_TenantId_EmployeeId_ClockInAt");

                    b.ToTable("attendance_records", "m2");
                });

            modelBuilder.Entity("M2.Domain.Authorization.AuthorizationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_authorization_roles_TenantId_Name");

                    b.ToTable("authorization_roles", "m2");
                });

            modelBuilder.Entity("M2.Domain.Authorization.ObjectFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FieldName");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FieldValue");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("RoleAuthorizationObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("RoleAuthorizationObjectId");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("RoleAuthorizationObjectId")
                        .HasDatabaseName("IX_object_field_values_RoleAuthorizationObjectId");

                    b.ToTable("object_field_values", "m2");
                });

            modelBuilder.Entity("M2.Domain.Authorization.RoleAuthorizationObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorizationObject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AuthorizationObject");

                    b.Property<Guid>("AuthorizationRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("AuthorizationRoleId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationRoleId")
                        .HasDatabaseName("IX_role_authorization_objects_AuthorizationRoleId");

                    b.HasIndex("AuthorizationRoleId", "AuthorizationObject")
                        .IsUnique()
                        .HasDatabaseName("IX_role_authorization_objects_RoleId_Object");

                    b.ToTable("role_authorization_objects", "m2");
                });

            modelBuilder.Entity("M2.Domain.Authorization.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("AuthorizationRoleId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UserId");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_user_role_assignments_TenantId_UserId");

                    b.HasIndex("UserId", "AuthorizationRoleId")
                        .HasDatabaseName("IX_user_role_assignments_UserId_RoleId");

                    b.ToTable("user_role_assignments", "m2");
                });

            modelBuilder.Entity("M2.Domain.GoodsReceipt.GoodsReceiptLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("DiscrepancyNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DiscrepancyNote");

                    b.Property<decimal>("ExpectedQty")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ExpectedQty");

                    b.Property<Guid>("GoodsReceiptNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("GoodsReceiptNoteId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ProductCode");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("ReceivedQty");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UnitOfMeasure");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptNoteId")
                        .HasDatabaseName("IX_goods_receipt_line_items_GoodsReceiptNoteId");

                    b.ToTable("goods_receipt_line_items", "m2");
                });

            modelBuilder.Entity("M2.Domain.GoodsReceipt.GoodsReceiptNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ConfirmedAt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("DiscrepancyNote")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ReceivedAt");

                    b.Property<string>("SapDeliveryNoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("SapDeliveryNoteNumber");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ShopId", "IsDeleted")
                        .HasDatabaseName("IX_goods_receipt_notes_TenantId_ShopId_IsDeleted");

                    b.HasIndex("TenantId", "ShopId", "Status")
                        .HasDatabaseName("IX_goods_receipt_notes_TenantId_ShopId_Status");

                    b.ToTable("goods_receipt_notes", "m2");
                });

            modelBuilder.Entity("M2.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("JoinedAt");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("MembershipTier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("QrCode");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("IX_members_QrCode");

                    b.HasIndex("TenantId", "Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_members_TenantId_Phone");

                    b.HasIndex("TenantId", "ShopId")
                        .HasDatabaseName("IX_members_TenantId_ShopId");

                    b.ToTable("members", "m2");
                });

            modelBuilder.Entity("M2.Domain.Members.OtpRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsUsed");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MemberId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "IsUsed")
                        .HasDatabaseName("IX_otp_requests_MemberId_IsUsed");

                    b.ToTable("otp_requests", "m2");
                });

            modelBuilder.Entity("M2.Domain.Notifications.DeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApnsToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ApnsToken");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("FcmToken");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Platform");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("RegisteredAt");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "Platform")
                        .IsUnique()
                        .HasDatabaseName("IX_device_registrations_TenantId_UserId_Platform");

                    b.ToTable("device_registrations", "m2");
                });

            modelBuilder.Entity("M2.Domain.Notifications.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ErrorMessage");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("RecipientUserId");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("SentAt");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("TemplateId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_notification_logs_TemplateId");

                    b.ToTable("notification_logs", "m2");
                });

            modelBuilder.Entity("M2.Domain.Notifications.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("notification_templates", "m2");
                });

            modelBuilder.Entity("M2.Domain.Promotions.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsRedeemed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRedeemed");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("IssuedAt");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MemberId");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("PromotionId");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("RedeemedAt");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_coupons_Code");

                    b.HasIndex("MemberId", "IsRedeemed")
                        .HasDatabaseName("IX_coupons_MemberId_IsRedeemed");

                    b.HasIndex("PromotionId", "IsRedeemed")
                        .HasDatabaseName("IX_coupons_PromotionId_IsRedeemed");

                    b.ToTable("coupons", "m2");
                });

            modelBuilder.Entity("M2.Domain.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovalRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApprovalRequestId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("EndDate");

                    b.Property<string>("FormulaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FormulaJson");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean")
                        .HasColumnName("IsStackable");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ShopId", "Status")
                        .HasDatabaseName("IX_promotions_TenantId_ShopId_Status");

                    b.ToTable("promotions", "m2");
                });

            modelBuilder.Entity("M2.Domain.Promotions.PromotionProduct", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("PromotionId");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ProductId");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("DiscountValue");

                    b.HasKey("PromotionId", "ProductId");

                    b.ToTable("promotion_products", "m2");
                });

            modelBuilder.Entity("M2.Domain.Sales.ReturnTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsComplete");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("OriginalTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalTransactionId");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ProcessedAt");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Reason");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("RefundAmount");

                    b.Property<string>("RefundMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RefundMethod");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("OriginalTransactionId");

                    b.ToTable("return_transactions", "m2");
                });

            modelBuilder.Entity("M2.Domain.Sales.SalesLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("DiscountAmount");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("LineTotal");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ProductId");

                    b.Property<string>("ProductNameEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ProductName_en");

                    b.Property<string>("ProductNameZht")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ProductName_zht");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("TransactionId");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("UnitPrice");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("sales_line_items", "m2");
                });

            modelBuilder.Entity("M2.Domain.Sales.SalesTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CashierId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CashierId");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("DiscountAmount");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("IdempotencyKey");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("MemberId");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PaymentMethod");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("VoidedAt");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_sales_transactions_MemberId");

                    b.HasIndex("TenantId", "ShopId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UIX_sales_transactions_TenantId_ShopId_IdempotencyKey")
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("TenantId", "ShopId", "Status")
                        .HasDatabaseName("IX_sales_transactions_TenantId_ShopId_Status");

                    b.ToTable("sales_transactions", "m2");
                });

            modelBuilder.Entity("M2.Domain.Sap.SapOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ErrorMessage");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Operation");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ProcessedAt");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("RetryCount");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("ShopId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_sap_outbox_entries_Status_CreatedAt");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_sap_outbox_entries_TenantId_Status");

                    b.ToTable("sap_outbox_entries", "m2");
                });

            modelBuilder.Entity("M2.Domain.Approvals.ApprovalStep", b =>
                {
                    b.HasOne("M2.Domain.Approvals.ApprovalRequest", null)
                        .WithMany("Steps")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Authorization.ObjectFieldValue", b =>
                {
                    b.HasOne("M2.Domain.Authorization.RoleAuthorizationObject", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("RoleAuthorizationObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Authorization.RoleAuthorizationObject", b =>
                {
                    b.HasOne("M2.Domain.Authorization.AuthorizationRole", null)
                        .WithMany("AuthorizationObjects")
                        .HasForeignKey("AuthorizationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.GoodsReceipt.GoodsReceiptLineItem", b =>
                {
                    b.HasOne("M2.Domain.GoodsReceipt.GoodsReceiptNote", null)
                        .WithMany("LineItems")
                        .HasForeignKey("GoodsReceiptNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("M2.SharedKernel.BilingualText", "ProductName", b1 =>
                        {
                            b1.Property<Guid>("GoodsReceiptLineItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ProductName_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ProductName_zht");

                            b1.HasKey("GoodsReceiptLineItemId");

                            b1.ToTable("goods_receipt_line_items", "m2");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptLineItemId");
                        });

                    b.Navigation("ProductName")
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Members.Member", b =>
                {
                    b.OwnsOne("M2.SharedKernel.BilingualText", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("FirstName_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("FirstName_zht");

                            b1.HasKey("MemberId");

                            b1.ToTable("members", "m2");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("M2.SharedKernel.BilingualText", "LastName", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("LastName_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("LastName_zht");

                            b1.HasKey("MemberId");

                            b1.ToTable("members", "m2");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Members.OtpRequest", b =>
                {
                    b.HasOne("M2.Domain.Members.Member", null)
                        .WithMany("OtpRequests")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Notifications.NotificationTemplate", b =>
                {
                    b.OwnsOne("M2.SharedKernel.BilingualText", "Body", b1 =>
                        {
                            b1.Property<Guid>("NotificationTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Body_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Body_zht");

                            b1.HasKey("NotificationTemplateId");

                            b1.ToTable("notification_templates", "m2");

                            b1.WithOwner()
                                .HasForeignKey("NotificationTemplateId");
                        });

                    b.OwnsOne("M2.SharedKernel.BilingualText", "Title", b1 =>
                        {
                            b1.Property<Guid>("NotificationTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Title_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Title_zht");

                            b1.HasKey("NotificationTemplateId");

                            b1.ToTable("notification_templates", "m2");

                            b1.WithOwner()
                                .HasForeignKey("NotificationTemplateId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Promotions.Coupon", b =>
                {
                    b.HasOne("M2.Domain.Promotions.Promotion", null)
                        .WithMany("Coupons")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Promotions.Promotion", b =>
                {
                    b.OwnsOne("M2.SharedKernel.BilingualText", "Name", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Name_en");

                            b1.Property<string>("Zht")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Name_zht");

                            b1.HasKey("PromotionId");

                            b1.ToTable("promotions", "m2");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Promotions.PromotionProduct", b =>
                {
                    b.HasOne("M2.Domain.Promotions.Promotion", null)
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Sales.ReturnTransaction", b =>
                {
                    b.HasOne("M2.Domain.Sales.SalesTransaction", null)
                        .WithMany()
                        .HasForeignKey("OriginalTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Sales.SalesLineItem", b =>
                {
                    b.HasOne("M2.Domain.Sales.SalesTransaction", null)
                        .WithMany("LineItems")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("M2.Domain.Approvals.ApprovalRequest", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("M2.Domain.Authorization.AuthorizationRole", b =>
                {
                    b.Navigation("AuthorizationObjects");
                });

            modelBuilder.Entity("M2.Domain.Authorization.RoleAuthorizationObject", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("M2.Domain.GoodsReceipt.GoodsReceiptNote", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("M2.Domain.Members.Member", b =>
                {
                    b.Navigation("OtpRequests");
                });

            modelBuilder.Entity("M2.Domain.Promotions.Promotion", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("M2.Domain.Sales.SalesTransaction", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
