// <auto-generated />
using System;
using M2.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace M2.Infrastructure.Migrations;

[DbContext(typeof(M2DbContext))]
[Migration("20260512010000_Sprint2_MembersApprovalsNotifications")]
partial class Sprint2_MembersApprovalsNotifications
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("m2")
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.UseIdentityByDefaultColumns();

        modelBuilder.Entity("M2.Domain.Members.Member", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<string>("Email")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("Email");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("IsActive");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<DateTimeOffset>("JoinedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("JoinedAt");

            b.Property<string>("MembershipTier")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("MembershipTier");

            b.Property<string>("Phone")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("Phone");

            b.Property<string>("QrCode")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("QrCode");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.HasKey("Id");

            b.HasIndex("QrCode")
                .IsUnique()
                .HasDatabaseName("IX_members_QrCode");

            b.HasIndex("TenantId", "Phone")
                .IsUnique()
                .HasDatabaseName("IX_members_TenantId_Phone");

            b.HasIndex("TenantId", "ShopId")
                .HasDatabaseName("IX_members_TenantId_ShopId");

            b.ToTable("members", "m2");

            b.OwnsOne("M2.SharedKernel.BilingualText", "FirstName", b1 =>
            {
                b1.Property<Guid>("MemberId")
                    .HasColumnType("uuid");

                b1.Property<string>("En")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("FirstName_en");

                b1.Property<string>("Zht")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("FirstName_zht");

                b1.HasKey("MemberId");
                b1.ToTable("members", "m2");
                b1.WithOwner().HasForeignKey("MemberId");
            });

            b.OwnsOne("M2.SharedKernel.BilingualText", "LastName", b1 =>
            {
                b1.Property<Guid>("MemberId")
                    .HasColumnType("uuid");

                b1.Property<string>("En")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("LastName_en");

                b1.Property<string>("Zht")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("LastName_zht");

                b1.HasKey("MemberId");
                b1.ToTable("members", "m2");
                b1.WithOwner().HasForeignKey("MemberId");
            });
        });

        modelBuilder.Entity("M2.Domain.Members.OtpRequest", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnType("character varying(6)")
                .HasColumnName("Code");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<DateTimeOffset>("ExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("ExpiresAt");

            b.Property<bool>("IsUsed")
                .HasColumnType("boolean")
                .HasColumnName("IsUsed");

            b.Property<Guid>("MemberId")
                .HasColumnType("uuid")
                .HasColumnName("MemberId");

            b.HasKey("Id");

            b.HasIndex("MemberId", "IsUsed")
                .HasDatabaseName("IX_otp_requests_MemberId_IsUsed");

            b.ToTable("otp_requests", "m2");
        });

        modelBuilder.Entity("M2.Domain.Approvals.ApprovalRequest", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<int>("CurrentStep")
                .HasColumnType("integer")
                .HasColumnName("CurrentStep");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<Guid>("EntityId")
                .HasColumnType("uuid")
                .HasColumnName("EntityId");

            b.Property<string>("EntityType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("EntityType");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("Status");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.HasKey("Id");

            b.ToTable("approval_requests", "m2");
        });

        modelBuilder.Entity("M2.Domain.Approvals.ApprovalStep", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<DateTimeOffset?>("ActedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("ActedAt");

            b.Property<string>("ApproverId")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("ApproverId");

            b.Property<string>("ApproverType")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("ApproverType");

            b.Property<string>("Comment")
                .HasColumnType("text")
                .HasColumnName("Comment");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<Guid>("RequestId")
                .HasColumnType("uuid")
                .HasColumnName("RequestId");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("Status");

            b.Property<int>("StepNumber")
                .HasColumnType("integer")
                .HasColumnName("StepNumber");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.HasKey("Id");

            b.HasIndex("RequestId")
                .HasDatabaseName("IX_approval_steps_RequestId");

            b.ToTable("approval_steps", "m2");
        });

        modelBuilder.Entity("M2.Domain.Approvals.ApprovalPolicy", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<string>("EntityType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("EntityType");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<int>("MaxLevels")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasDefaultValue(2)
                .HasColumnName("MaxLevels");

            b.Property<string>("Mode")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("Mode");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.HasKey("Id");

            b.HasIndex("TenantId", "EntityType")
                .IsUnique()
                .HasDatabaseName("IX_approval_policies_TenantId_EntityType");

            b.ToTable("approval_policies", "m2");
        });

        modelBuilder.Entity("M2.Domain.Notifications.NotificationTemplate", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("Type");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.HasKey("Id");

            b.ToTable("notification_templates", "m2");

            b.OwnsOne("M2.SharedKernel.BilingualText", "Title", b1 =>
            {
                b1.Property<Guid>("NotificationTemplateId")
                    .HasColumnType("uuid");

                b1.Property<string>("En")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("Title_en");

                b1.Property<string>("Zht")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("Title_zht");

                b1.HasKey("NotificationTemplateId");
                b1.ToTable("notification_templates", "m2");
                b1.WithOwner().HasForeignKey("NotificationTemplateId");
            });

            b.OwnsOne("M2.SharedKernel.BilingualText", "Body", b1 =>
            {
                b1.Property<Guid>("NotificationTemplateId")
                    .HasColumnType("uuid");

                b1.Property<string>("En")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("Body_en");

                b1.Property<string>("Zht")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("Body_zht");

                b1.HasKey("NotificationTemplateId");
                b1.ToTable("notification_templates", "m2");
                b1.WithOwner().HasForeignKey("NotificationTemplateId");
            });
        });

        modelBuilder.Entity("M2.Domain.Notifications.DeviceRegistration", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<string>("ApnsToken")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("ApnsToken");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("CreatedAt");

            b.Property<string>("CreatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("CreatedBy");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("DeletedAt");

            b.Property<string>("DeletedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("DeletedBy");

            b.Property<string>("FcmToken")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("FcmToken");

            b.Property<bool>("IsDeleted")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(false)
                .HasColumnName("IsDeleted");

            b.Property<string>("Platform")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("Platform");

            b.Property<DateTimeOffset>("RegisteredAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("RegisteredAt");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("ShopId");

            b.Property<Guid>("TenantId")
                .HasColumnType("uuid")
                .HasColumnName("TenantId");

            b.Property<DateTimeOffset?>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("UpdatedAt");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UpdatedBy");

            b.Property<string>("UserId")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("UserId");

            b.HasKey("Id");

            b.HasIndex("TenantId", "UserId", "Platform")
                .IsUnique()
                .HasDatabaseName("IX_device_registrations_TenantId_UserId_Platform");

            b.ToTable("device_registrations", "m2");
        });

        modelBuilder.Entity("M2.Domain.Notifications.NotificationLog", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("Id");

            b.Property<string>("ErrorMessage")
                .HasColumnType("text")
                .HasColumnName("ErrorMessage");

            b.Property<Guid>("NotificationTemplateId")
                .HasColumnType("uuid")
                .HasColumnName("NotificationTemplateId");

            b.Property<string>("RecipientUserId")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("RecipientUserId");

            b.Property<DateTimeOffset>("SentAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("SentAt");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("Status");

            b.HasKey("Id");

            b.HasIndex("NotificationTemplateId")
                .HasDatabaseName("IX_notification_logs_NotificationTemplateId");

            b.ToTable("notification_logs", "m2");
        });

        // ── relationships ────────────────────────────────────────────────────
        modelBuilder.Entity("M2.Domain.Members.OtpRequest", b =>
        {
            b.HasOne("M2.Domain.Members.Member", "Member")
                .WithMany("OtpRequests")
                .HasForeignKey("MemberId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("M2.Domain.Approvals.ApprovalStep", b =>
        {
            b.HasOne("M2.Domain.Approvals.ApprovalRequest", "ApprovalRequest")
                .WithMany("Steps")
                .HasForeignKey("RequestId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("M2.Domain.Notifications.NotificationLog", b =>
        {
            b.HasOne("M2.Domain.Notifications.NotificationTemplate", "Template")
                .WithMany("Logs")
                .HasForeignKey("NotificationTemplateId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
