import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/auth/auth_service.dart';
import 'core/l10n/locale_provider.dart';
import 'features/home/home_screen.dart';
import 'features/login/login_screen.dart';
import 'shared/theme/app_theme.dart';

// Generated by `flutter gen-l10n`
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class MekaPromosApp extends ConsumerWidget {
  const MekaPromosApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);
    final locale = ref.watch(localeProvider);

    return MaterialApp(
      title: 'Meka Promos',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      locale: locale,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      // Member app supports ZHT / ZHS / EN (ADR-022)
      supportedLocales: const [
        Locale('zh'),           // ZHT (Traditional Chinese)
        Locale('zh', 'Hans'),   // ZHS (Simplified Chinese)
        Locale('en'),           // EN
      ],
      home: authState.when(
        data: (user) => user != null ? const HomeScreen() : const LoginScreen(),
        loading: () => const _SplashScreen(),
        error: (_, __) => const LoginScreen(),
      ),
    );
  }
}

class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: CircularProgressIndicator()),
    );
  }
}
