import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'core/l10n/locale_provider.dart';
import 'features/home/home_screen.dart';
import 'features/login/login_screen.dart';
import 'features/login/login_otp_screen.dart';
import 'features/registration/registration_screen.dart';
import 'features/registration/otp_verification_screen.dart';
import 'features/registration/profile_setup_screen.dart';
import 'features/profile/edit_profile_screen.dart';
import 'features/profile/profile_service.dart';
import 'shared/theme/app_theme.dart';

// Generated by `flutter gen-l10n`
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class MekaPromosApp extends ConsumerStatefulWidget {
  const MekaPromosApp({super.key});

  @override
  ConsumerState<MekaPromosApp> createState() => _MekaPromosAppState();
}

class _MekaPromosAppState extends ConsumerState<MekaPromosApp> {
  late final GoRouter _router;
  final _refresher = _RouterRefresher();

  @override
  void initState() {
    super.initState();
    _router = GoRouter(
      initialLocation: '/registration',
      refreshListenable: _refresher,
      redirect: (context, state) {
        final session = ref.read(memberSessionProvider);
        final isAuthed = session != null;
        final isOnboarding =
            state.matchedLocation.startsWith('/registration') ||
            state.matchedLocation.startsWith('/login');
        if (!isAuthed && !isOnboarding) return '/registration';
        if (isAuthed && isOnboarding) return '/';
        return null;
      },
      routes: [
        GoRoute(
          path: '/',
          builder: (_, __) => const HomeScreen(),
        ),
        GoRoute(
          path: '/registration',
          builder: (_, __) => const RegistrationScreen(),
        ),
        GoRoute(
          path: '/registration/otp',
          builder: (_, state) =>
              OtpVerificationScreen(phone: state.extra as String),
        ),
        GoRoute(
          path: '/registration/profile',
          builder: (_, state) =>
              ProfileSetupScreen(verificationToken: state.extra as String),
        ),
        GoRoute(
          path: '/profile/edit',
          builder: (_, __) => const EditProfileScreen(),
        ),
        GoRoute(
          path: '/login',
          builder: (_, __) => const LoginScreen(),
        ),
        GoRoute(
          path: '/login/otp',
          builder: (_, state) {
            final extra = state.extra as Map<String, String>;
            return LoginOtpScreen(
              phone: extra['phone']!,
              memberId: extra['memberId']!,
            );
          },
        ),
      ],
    );
  }

  @override
  void dispose() {
    _router.dispose();
    _refresher.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // Trigger router refresh whenever session auth state changes.
    ref.listen(memberSessionProvider, (_, __) => _refresher.refresh());
    final locale = ref.watch(localeProvider);

    return MaterialApp.router(
      routerConfig: _router,
      title: 'Meka Promos',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      locale: locale as Locale?,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      // Member app supports ZHT / ZHS / EN (ADR-022)
      supportedLocales: const [
        Locale('zh'),          // ZHT (Traditional Chinese)
        Locale('zh', 'Hans'),  // ZHS (Simplified Chinese)
        Locale('en'),          // EN
      ],
    );
  }
}

class _RouterRefresher extends ChangeNotifier {
  void refresh() => notifyListeners();
}

